# Generated by Django 5.0.7 on 2026-01-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_post_impressions_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_messages', to='jobportal.post'),
        ),
    ]
