# Generated by Django 5.0.7 on 2026-01-20 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_message_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='connections',
            field=models.ManyToManyField(blank=True, to='jobportal.userprofile'),
        ),
    ]
