# Generated by Django 5.0.7 on 2026-01-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_company_followers_userprofile_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='commute',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
