# Generated by Django 5.0.7 on 2026-01-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills required for this job', null=True),
        ),
    ]
