# Generated by Django 5.0.7 on 2026-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
