"""
Django settings for internship project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os  # Make sure this is imported at the top if needed (usually not needed for BASE_DIR / 'templates')
from pathlib import Path
# ==========================================
# PASTE THIS AT THE VERY END OF settings.py
# ==========================================

import os
from django.utils.translation import gettext_lazy as _

# 1. Define Supported Languages
LANGUAGES = [
    ('en-gb', _('English (UK)')),
    ('de', _('German')),
    ('zh-hans', _('Chinese (Simplified)')),
    ('hi', _('Hindi')),
    ('gu', _('Gujarati')),
    ('mr', _('Marathi')),
    ('bn', _('Bengali')),
    ('ta', _('Tamil')),
    ('te', _('Telugu')),
    ('kn', _('Kannada')),
    ('ml', _('Malayalam')),
    ('pa', _('Punjabi')),
    ('ur', _('Urdu')),
]

# 2. Define where translation files live


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_0$8_l^1vxysc92o&1tn^6b+6x(eo7(7173@3alh86s!80-v1m'

# Email Configuration - Using Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'solankipriyanshu198@gmail.com'
EMAIL_HOST_PASSWORD = 'purl sxpb xqzp fxxk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# settings.py

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '751752402385-979qquoil594tsd98r9hpgv35calm7m5.apps.googleusercontent.com',
            'secret': 'PASTE_YOUR_CLIENT_SECRET_HERE',  # <--- You must paste the secret from the Google Console here
            'key': ''
        }
    }
}



# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'jobportal', 

    # --- ADD THESE 5 NEW LINES BELOW ---
    'django.contrib.sites',  
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# --- ADD THIS LINE AT THE BOTTOM OF THE FILE ---
SITE_ID = 1
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # <--- ADD THIS LINE HERE
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


# Add these at the bottom:
RECAPTCHA_PUBLIC_KEY = '6LfSfFwsAAAAAEXILxWVB0fk_kmQVFke7h72x9U2'
RECAPTCHA_PRIVATE_KEY = '6LfSfFwsAAAAAOheZ91JQwuShepRjt-C71YLWlj8'

# --- AUTHENTICATION SETTINGS ---

# If a user is NOT logged in and tries to visit a protected page, send them here:
LOGIN_URL = 'login' 

# After a successful login, send them here:
LOGIN_REDIRECT_URL = 'home'

# After logout, send them here:
LOGOUT_REDIRECT_URL = 'login'
ROOT_URLCONF = 'internship.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # CHANGE THIS LINE:
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# settings.py

# CHANGE THESE TO FALSE for localhost development
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

WSGI_APPLICATION = 'internship.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Security: Log user out when they close the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Security: Log user out after 30 minutes of inactivity (Optional)
SESSION_COOKIE_AGE = 1800

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ... (all your other settings above) ...

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 👇 ADD THIS AT THE VERY BOTTOM 👇
import os
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')